/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import clases.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author juan_
 */
public class AnalisisBivariable extends javax.swing.JFrame {

    int indiceVariable1;
    int indiceVariable2;
    DataSet baseDatos;
    CoeficienteCorrelacion calculos = new CoeficienteCorrelacion();

    public AnalisisBivariable(int atributo1, int atributo2, DataSet baseDatos) {
        initComponents();
        this.indiceVariable1 = atributo1;
        this.indiceVariable2 = atributo2;
        this.baseDatos = baseDatos;

        // Create dataset
        XYDataset dataset = createDataset();
        String nombre1 = baseDatos.getAtributos().get(indiceVariable1).getNombre();
        String nombre2 = baseDatos.getAtributos().get(indiceVariable2).getNombre();
        // Create chart
        JFreeChart chart = ChartFactory.createScatterPlot(
                "Diagrama de Dispersion " + nombre1 + " vs " + nombre2,
                "X-" + nombre1, "Y-" + nombre2, dataset);

        //Changes background color
        XYPlot plot = (XYPlot) chart.getPlot();
        plot.setBackgroundPaint(new Color(255, 228, 196));

        // Create Panel
        ChartPanel panel = new ChartPanel(chart);
        panel.setSize(panelGrafica.getWidth(), panelGrafica.getHeight());
        panel.setVisible(true);
        panelGrafica.add(panel);
        panelGrafica.repaint();

        //setContentPane(panel);
        //Calculo del Coeficiente de Correlacion
        int valorX;
        int valorY;
        for (int i = 0; i < baseDatos.getNumInstancias(); i++) {
            valorX = Integer.parseInt(baseDatos.getAtributos().get(indiceVariable1).getInstancias().get(i));
            valorY = Integer.parseInt(baseDatos.getAtributos().get(indiceVariable2).getInstancias().get(i));
            calculos.getListaX().add(valorX);
            calculos.getListaY().add(valorY);
        }
        calculos.calcularVariables();
        calculos.calcularTotal();
        calculos.calcularDesviacion();
        calculos.calcularCoeficienteCorrelacion();
        this.actualizarTextArea();
    }

    private XYDataset createDataset() {
        XYSeriesCollection dataset = new XYSeriesCollection();

        //Boys (Age,weight) series
        XYSeries series1 = new XYSeries("Relacion");
        int valorX;
        int valorY;
        for (int i = 0; i < baseDatos.getNumInstancias(); i++) {
            valorX = Integer.parseInt(baseDatos.getAtributos().get(indiceVariable1).getInstancias().get(i));
            valorY = Integer.parseInt(baseDatos.getAtributos().get(indiceVariable2).getInstancias().get(i));
            series1.add(valorX, valorY);
        }
        dataset.addSeries(series1);
        return dataset;
    }

    public void actualizarTextArea() {
        textAreaDatos.setText("");
        textAreaDatos.append("Coeficiente de Correlacion: " + calculos.getCoeficienteCorrelacion() + "\n");
        textAreaDatos.append("Desviacion Estandar de X: " + calculos.getDesviacionEstandarX() + "\n");
        textAreaDatos.append("Desviacion Estandar de Y: " + calculos.getDesviacionEstandarY() + "\n");
        textAreaDatos.append("Desviacion Estandar de XY: " + calculos.getDesviacionEstandarXY() + "\n");
        textAreaDatos.append("Total de X: " + calculos.getTotalX() + "\n");
        textAreaDatos.append("Total de Y: " + calculos.getTotalY() + "\n");
        textAreaDatos.append("Total de XY: " + calculos.getTotalXY() + "\n");
        textAreaDatos.append("Total de X2: " + calculos.getTotalX2() + "\n");
        textAreaDatos.append("Total de Y2: " + calculos.getTotalY2() + "\n");
        textAreaDatos.append("Media de X: " + calculos.getMediaX() + "\n");
        textAreaDatos.append("Media de Y: " + calculos.getMediaY() + "\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGrafica = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDatos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelGrafica.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textAreaDatos.setEditable(false);
        textAreaDatos.setColumns(20);
        textAreaDatos.setRows(5);
        jScrollPane1.setViewportView(textAreaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 207, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGrafica;
    private javax.swing.JTextArea textAreaDatos;
    // End of variables declaration//GEN-END:variables
}
